### PR TITLE
Pull out commenting into a separate crate, simplify WebServer -> App communication

### PR DESCRIPTION
**Pull request by acmcarther**

### CODE REVIEW

**Comment by acmcarther** [comment]
This code is already deployed (to smoketest).

Here goes a smoketest 

pt r?

**Comment by pt-195** [comment]
PTBOT: Assigning @seanstrom @rschifflin to this PR

**Comment by acmcarther** [comment]
git 2 it m80s ^^

By the way, wow testing good job. One try, one success.

**Comment by acmcarther** [comment]
I'm going to merge this to permit more work to get done (hopefully that will become less necessary). If anyone has any comments, feel free to make them here and I'll make a subsequent PR for them.

**Pull request closed without merging**
